function updateCardGradient(e,t){let n=hexToRgb(t),a=lightenColor(n,30),l=rgbToHex(a.r,a.g,a.b);e.style.setProperty("--card-gradient",`linear-gradient(var(--rotate), ${l}, ${t} 43%, ${darkenColor(t)})`)}function hexToRgb(e){e=e.replace(/^#/,"");let t=parseInt(e,16);return{r:t>>16&255,g:t>>8&255,b:255&t}}function rgbToHex(e,t,n){return`#${(16777216+(e<<16)+(t<<8)+n).toString(16).slice(1)}`}function lightenColor(e,t){return{r:Math.min(255,Math.floor(e.r*(1+t/100))),g:Math.min(255,Math.floor(e.g*(1+t/100))),b:Math.min(255,Math.floor(e.b*(1+t/100)))}}function darkenColor(e){let t=hexToRgb(e),n={r:Math.max(0,Math.floor(.7*t.r)),g:Math.max(0,Math.floor(.7*t.g)),b:Math.max(0,Math.floor(.7*t.b))};return rgbToHex(n.r,n.g,n.b)}function addDeleteDatabaseCard(){let e=document.getElementById("cardsContainer"),t=document.createElement("div");t.className="card delete-card",t.setAttribute("data-color","#e33c3c");let n=document.createElement("div");n.className="card-content";let a=document.createElement("div");a.className="trash-icon",a.innerHTML=`
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <polyline points="3 6 5 6 21 6"></polyline>
            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
            <line x1="10" y1="11" x2="10" y2="17"></line>
            <line x1="14" y1="11" x2="14" y2="17"></line>
        </svg>
    `;let l=document.createElement("h2");l.textContent="Supprimer tout";let r=document.createElement("p");r.className="card-explanation",r.textContent="Effacer toutes les cartes de la base de donn\xe9es",n.appendChild(a),n.appendChild(l),n.appendChild(r),t.appendChild(n),updateCardGradient(t,"#e33c3c"),t.addEventListener("click",function(){confirmDeleteAllCards()}),e.appendChild(t)}function confirmDeleteAllCards(){let e=document.createElement("div");e.className="modal",e.id="confirmDeleteModal";let t=document.createElement("div");t.className="modal-content delete-confirm-modal";let n=document.createElement("span");n.className="close-modal",n.innerHTML="&times;";let a=document.createElement("div");a.className="warning-icon",a.innerHTML=`
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path>
            <line x1="12" y1="9" x2="12" y2="13"></line>
            <line x1="12" y1="17" x2="12.01" y2="17"></line>
        </svg>
    `;let l=document.createElement("h2");l.textContent="Attention !";let r=document.createElement("p");r.textContent="Vous \xeates sur le point de supprimer toutes vos cartes. Cette action est irr\xe9versible. Voulez-vous continuer ?";let o=document.createElement("div");o.className="confirm-buttons";let d=document.createElement("button");d.className="cancel-btn",d.textContent="Annuler";let i=document.createElement("button");i.className="confirm-btn",i.textContent="Supprimer tout",o.appendChild(d),o.appendChild(i),t.appendChild(n),t.appendChild(a),t.appendChild(l),t.appendChild(r),t.appendChild(o),e.appendChild(t),document.body.appendChild(e),e.style.display="block",n.addEventListener("click",function(){e.style.display="none",setTimeout(()=>{document.body.removeChild(e)},300)}),d.addEventListener("click",function(){e.style.display="none",setTimeout(()=>{document.body.removeChild(e)},300)}),i.addEventListener("click",function(){let t=document.querySelectorAll(".card:not(.add-card):not(.info-card):not(.delete-card)");t.forEach(e=>e.remove()),window.allCards=[],localStorage.setItem("animatedCards",JSON.stringify([]));let n=document.createElement("div");n.className="success-message",n.textContent="Toutes les cartes ont \xe9t\xe9 supprim\xe9es avec succ\xe8s !",document.querySelector(".container").appendChild(n),setTimeout(()=>{n.classList.add("fade-out"),setTimeout(()=>{document.querySelector(".container").removeChild(n)},500)},3e3),e.style.display="none",setTimeout(()=>{document.body.removeChild(e)},300)}),window.addEventListener("click",function(t){t.target===e&&(e.style.display="none",setTimeout(()=>{document.body.removeChild(e)},300))})}document.addEventListener("DOMContentLoaded",function(){"undefined"!=typeof initExistingCards?setTimeout(()=>{addDeleteDatabaseCard()},100):window.addEventListener("load",function(){setTimeout(()=>{addDeleteDatabaseCard()},500)})});